POST http://localhost:3333/events
Content-Type:  application/json

{
    "title": "evento testcdf",
    "details": "evento realizado para o teste do aplicativo",
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/a5ab41e5-3249-4419-8866-b43039ea7a86/attendees
Content-Type: application/json

{
   "name":"Jodhn Doed",
   "email":"johnd@doedssd.com"
   
}